### PR TITLE
Attach ctx

### PR DESCRIPTION
**Pull request by dylanhitt**
Took a pass at the utility function of `handleCtx` to limit some of the boiler plate. Let me know what you think.

### CODE REVIEW

**Comment by dylanhitt** [comment]
@NSEcho Any thoughts on the above

**Comment by NSEcho** [comment]
Hey @dylanhitt, I didn't have much time to take a look at this, I will get to it over the weekend.

**Comment by NSEcho** [comment]
Hi @dylanhitt, could you please instead of `ParamsCtx` use `ParamsWithContext` convention throughout the code, otherwise looking okay

**Comment by dylanhitt** [comment]
Sure I'll get to it tomorrow.

**Comment by dylanhitt** [comment]
I think that should do it. 

Thank you

**Comment by NSEcho** [comment]
Thanks @dylanhitt

**Pull request merged**
